apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-ixpcsdll
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-ixpcsdll 
  name: go-ixpcsdll
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-ixpcsdll
    weight: 100 
